#!/bin/bash
red=$'\e[0;31m'
grn=$'\e[1;32m'
yel=$'\e[1;33m'
blu=$'\e[1;34m'
mag=$'\e[1;35m'
cyn=$'\e[1;36m'
end=$'\e[0m'

STAGED_FILES_CSS=$(git diff --cached --name-only --diff-filter=ACM | grep -oE "(([a-zA-Z_/-]*)(.css|.scss|.sass)){0,1}$")
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -oE "(([a-zA-Z_/-]*)(.js|.vue)){0,1}$")

eslint="./node_modules/eslint/bin/eslint.js"
list=`echo ${STAGED_FILES} | awk 'BEGIN { ORS = " " } { print }'`
result=`${eslint} ${list}`

errors=`echo ${result} | grep -E "[0-9]:[0-9] error"`
files=`echo ${result} | grep -oE "[/a-zA-Z0-9_\-]+/[a-zA-Z_]+.(js|vue)"`

pass=0

if [ ! -z "$STAGED_FILES"]
then
    printf "\n${yel}RUNNING JS AND VUE LINTERS${end}\n"
    if [ ! -z "$errors" ]
    then
        list=`echo ${STAGED_FILES} | awk 'BEGIN { ORS = " " } { print }'`
        ${eslint} ${list}
        printf "\n${red}ESLINT FAILED\nTRY RUNNING \"npm run js-fix\" AND COMMIT AGAIN.${end}\n"
        pass=1
    else
        printf "${grn}Eslint says it looks good!${end}\n"
    fi

fi

stylelint="./node_modules/stylelint/bin/stylelint.js"
if [ ! -z "$STAGED_FILES_CSS" ]
then
    printf "\n${yel}RUNNING SASS LINTERS${end}\n"
    list=`echo ${STAGED_FILES_CSS} | awk 'BEGIN { ORS = " " } { print }'`
    result=`${stylelint} ${list}`
    errors=`echo ${result} | grep -E "[0-9]:[0-9]"`
    printf "$errors"
    if [ ! -z "$errors" ]
    then
        ${stylelint} ${list}
        printf "\n${red}SASS LINTER FAILED. Try to fix it with \"npm run sass-fix\" and commit again.${end}\n"
        pass=1
    else
        printf "${grn}SASS linters says it looks good!${end}\n"
    fi
fi

exit ${pass}