#!/bin/bash
STAGED_FILES_CSS=$(git diff --cached --name-only --diff-filter=ACM | grep -oE "(([a-zA-Z_/-]*)(.css|.scss|.sass)){0,1}$")

stylelint="./node_modules/stylelint/bin/stylelint.js"

list=`echo ${STAGED_FILES_CSS} | awk 'BEGIN { ORS = " " } { print }'`

${stylelint} ${list} --fix

exit 0